version: "3.1"
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      # To persis sql data use one of this options, I recomended using a docker volumen instead of a direct folder, but option 2 is the easiest
      # option 1: with desined volume
      # - db_data:/var/lib/mysql
      # option 2: with a local direcory inside the same folder
      - ./db_data:/var/lib/mysql
      # this forlder have to contain all initial script and sql to be imported and run at the first time db run up
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ROOT_PASSWORD
      MYSQL_DATABASE: MYSQL_DBNAME
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - "3306:3306"
  web:
    image: wordpress
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: WORDPRESS_DB_NAME
      WORDPRESS_DB_USER: WORDPRESS_DB_USER
      WORDPRESS_DB_PASSWORD: WORDPRESS_DB_PASSWORD
      LOCALDEV: "TRUE"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ROOT_PASSWORD
# volumes:
#   db_data